name: GitClaude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  request-review:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
    
    steps:
      - name: Request GitClaude Review
        uses: actions/github-script@v6
        with:
          script: |
            // Only run on PR events or when GitClaude is mentioned
            if (context.eventName === 'pull_request') {
              console.log('New PR activity detected, GitClaude will be notified');
            } else if (context.eventName === 'issue_comment') {
              console.log('GitClaude mentioned in comment');
            }
            
      - name: Add Review Label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['awaiting-gitclaude-review']
            })